### ISSUE TITLE
Relation to new vobject

### ISSUE THREAD

**Issue by jspricke** [tBaxter/python-card-me#10]
Hi,

seems like vobject finally got an update (https://pypi.python.org/pypi/vobject/0.9.2) and it seems to be in good shape. What's the relation to card-me? I think it would be great to merge both projects again, what do you think?

**Comment by tBaxter** [comment]
They pulled mine in. I thought it was kind of interesting that the day
after I announced Python-card-me, there was all of sudden a new vobject
maintainer announced. Right now, I'm kind of waiting to see if they
actually _do_ anything with it beyond just merging my code, or if it
stagnates again.
